import { createSlice } from "@reduxjs/toolkit";

// initializing state
const initialState = {
  numOfCakes: 10,
};

// creating slice
const cakeSlice = createSlice({
  name: "cake",
  initialState,
  // reducer is a function which updates or mutate state based on action
  reducers: {
    // action creators
    ordered: (state) => {
      // directly mutating or updating the state
      state.numOfCakes--;
    },
    restocked: (state, action) => {
      state.numOfCakes += action.payload;
    },
  },
});

//root reducer generated by createSlice()
const cakeRootReducer = cakeSlice.reducer;
export default cakeRootReducer;

// action creators
export const { ordered, restocked } = cakeSlice.actions;
